export const ACTIONS_TYPES = {
  CHANGE_NUMBER: "CHANGE_NUMBER",
  CHANGE_NAME: "CHANGE_NAME",
  CHANGE_EXPIRATION_MONTH: "CHANGE_EXPIRATION_MONTH",
  CHANGE_EXPIRATION_YEAR: "CHANGE_EXPIRATION_YEAR",
  CHANGE_CVV: 'CHABGE_CVV',
  SET_CARD_DATA: 'SET_CARD_DATA',
  
  CHANGE_CARD_TYPE: "CHANGE_CARD_TYPE",
  SET_CARD: "SET_CARD",
  FRONT_SIDE: "FRONT_SIDE",
  SET_ANIMATION: "SET_ANIMATION",
  SET_MIRROR: "SET_MIRROR",

  SET_LOADING: "SET_LOADING",
  SET_BTN_DISABLE: "SET_BTN_DISABLE"
}